Update build-openwrt.yml

diff --git a/.github/workflows/build-openwrt.yml b/.github/workflows/build-openwrt.yml
--- a/.github/workflows/build-openwrt.yml
+++ b/.github/workflows/build-openwrt.yml
@@ -221,22 +221,38 @@ jobs:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
     #- name: 安装 telegram-send
-    #  run: pip install telegram-send && telegram-send --configure
+#      env:
+#        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
+#        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
+#      #run: pip3 install telegram-send && telegram-send --configure --token $TELEGRAM_BOT_TOKEN
+#      run: telegram-send --configure --token $TELEGRAM_BOT_TOKEN
 
-   # - name: Telegram Bot 通知
-   #   if: always()
-   #   env:
-   #     TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
-    #    TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
-    #  run: |
-   #     if [ -z "$TELEGRAM_CHAT_ID" ] || [ -z "$TELEGRAM_BOT_TOKEN" ]; then
-    #      echo "Telegram notifications are not configured. Skipping..."
-   #       exit 0
-    #    fi
-   #     status="GitHub Actions Build OpenWrt Status:
-    #      Repository: ${{ github.repository }}
-   #       Workflow: ${{ github.workflow }}
-   #       Event: ${{ github.event_name }}
-  #        Status: ${{ job.status }}"
-  #      [ -z "$TELEGRAM_BOT_TOKEN" ] || telegram-send "$status"
-  #      [ -z "$TELEGRAM_BOT_TOKEN" ] || curl -s "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" -d "chat_id=$TELEGRAM_CHAT_ID&text=$status"
+    - name: Telegram Bot 通知
+      if: always()
+      env:
+        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
+        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
+      run: |
+        if [ -z "$TELEGRAM_CHAT_ID" ] || [ -z "$TELEGRAM_BOT_TOKEN" ]; then
+          echo "Telegram notifications are not configured. Skipping..."
+          exit 0
+        fi
+        telegram-send --configure --token $TELEGRAM_BOT_TOKEN
+        status="GitHub Actions Build OpenWrt Status:
+          Repository: ${{ github.repository }}
+          Workflow: ${{ github.workflow }}
+          Event: ${{ github.event_name }}
+          Status: ${{ job.status }}"
+        [ -z "$TELEGRAM_BOT_TOKEN" ] || telegram-send "$status"
+        [ -z "$TELEGRAM_BOT_TOKEN" ] || curl -s "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" -d "chat_id=$TELEGRAM_CHAT_ID&text=$status"
+
+        
+#- name: Configure telegram-send
+#  env:
+#    TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
+#  run: |
+#    if [ -z "$TELEGRAM_BOT_TOKEN" ]; then
+#      echo "Telegram Bot Token is not configured. Cannot run telegram-send --configure."
+#      exit 1
+#    fi
+#    telegram-send --configure --token $TELEGRAM_BOT_TOKEN
